/**
 * @fileoverview gRPC-Web generated client stub for hotelPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: src/hotel.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.hotelPackage = require('./hotel_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hotelPackage.HotelsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hotelPackage.HotelsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hotelPackage.Location,
 *   !proto.hotelPackage.HotelList>}
 */
const methodDescriptor_Hotels_getHotels = new grpc.web.MethodDescriptor(
  '/hotelPackage.Hotels/getHotels',
  grpc.web.MethodType.UNARY,
  proto.hotelPackage.Location,
  proto.hotelPackage.HotelList,
  /**
   * @param {!proto.hotelPackage.Location} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hotelPackage.HotelList.deserializeBinary
);


/**
 * @param {!proto.hotelPackage.Location} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hotelPackage.HotelList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hotelPackage.HotelList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hotelPackage.HotelsClient.prototype.getHotels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hotelPackage.Hotels/getHotels',
      request,
      metadata || {},
      methodDescriptor_Hotels_getHotels,
      callback);
};


/**
 * @param {!proto.hotelPackage.Location} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hotelPackage.HotelList>}
 *     Promise that resolves to the response
 */
proto.hotelPackage.HotelsPromiseClient.prototype.getHotels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hotelPackage.Hotels/getHotels',
      request,
      metadata || {},
      methodDescriptor_Hotels_getHotels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hotelPackage.HotelFilters,
 *   !proto.hotelPackage.HotelList>}
 */
const methodDescriptor_Hotels_filterHotels = new grpc.web.MethodDescriptor(
  '/hotelPackage.Hotels/filterHotels',
  grpc.web.MethodType.UNARY,
  proto.hotelPackage.HotelFilters,
  proto.hotelPackage.HotelList,
  /**
   * @param {!proto.hotelPackage.HotelFilters} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hotelPackage.HotelList.deserializeBinary
);


/**
 * @param {!proto.hotelPackage.HotelFilters} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hotelPackage.HotelList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hotelPackage.HotelList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hotelPackage.HotelsClient.prototype.filterHotels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hotelPackage.Hotels/filterHotels',
      request,
      metadata || {},
      methodDescriptor_Hotels_filterHotels,
      callback);
};


/**
 * @param {!proto.hotelPackage.HotelFilters} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hotelPackage.HotelList>}
 *     Promise that resolves to the response
 */
proto.hotelPackage.HotelsPromiseClient.prototype.filterHotels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hotelPackage.Hotels/filterHotels',
      request,
      metadata || {},
      methodDescriptor_Hotels_filterHotels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hotelPackage.Hotel,
 *   !proto.hotelPackage.HotelDetails>}
 */
const methodDescriptor_Hotels_getHotelDetails = new grpc.web.MethodDescriptor(
  '/hotelPackage.Hotels/getHotelDetails',
  grpc.web.MethodType.UNARY,
  proto.hotelPackage.Hotel,
  proto.hotelPackage.HotelDetails,
  /**
   * @param {!proto.hotelPackage.Hotel} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hotelPackage.HotelDetails.deserializeBinary
);


/**
 * @param {!proto.hotelPackage.Hotel} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hotelPackage.HotelDetails)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hotelPackage.HotelDetails>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hotelPackage.HotelsClient.prototype.getHotelDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hotelPackage.Hotels/getHotelDetails',
      request,
      metadata || {},
      methodDescriptor_Hotels_getHotelDetails,
      callback);
};


/**
 * @param {!proto.hotelPackage.Hotel} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hotelPackage.HotelDetails>}
 *     Promise that resolves to the response
 */
proto.hotelPackage.HotelsPromiseClient.prototype.getHotelDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hotelPackage.Hotels/getHotelDetails',
      request,
      metadata || {},
      methodDescriptor_Hotels_getHotelDetails);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hotelPackage.Hotel,
 *   !proto.hotelPackage.HotelDetails>}
 */
const methodDescriptor_Hotels_saveFavorite = new grpc.web.MethodDescriptor(
  '/hotelPackage.Hotels/saveFavorite',
  grpc.web.MethodType.UNARY,
  proto.hotelPackage.Hotel,
  proto.hotelPackage.HotelDetails,
  /**
   * @param {!proto.hotelPackage.Hotel} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hotelPackage.HotelDetails.deserializeBinary
);


/**
 * @param {!proto.hotelPackage.Hotel} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hotelPackage.HotelDetails)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hotelPackage.HotelDetails>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hotelPackage.HotelsClient.prototype.saveFavorite =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hotelPackage.Hotels/saveFavorite',
      request,
      metadata || {},
      methodDescriptor_Hotels_saveFavorite,
      callback);
};


/**
 * @param {!proto.hotelPackage.Hotel} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hotelPackage.HotelDetails>}
 *     Promise that resolves to the response
 */
proto.hotelPackage.HotelsPromiseClient.prototype.saveFavorite =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hotelPackage.Hotels/saveFavorite',
      request,
      metadata || {},
      methodDescriptor_Hotels_saveFavorite);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hotelPackage.noParams,
 *   !proto.hotelPackage.HotelList>}
 */
const methodDescriptor_Hotels_getFavorite = new grpc.web.MethodDescriptor(
  '/hotelPackage.Hotels/getFavorite',
  grpc.web.MethodType.UNARY,
  proto.hotelPackage.noParams,
  proto.hotelPackage.HotelList,
  /**
   * @param {!proto.hotelPackage.noParams} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.hotelPackage.HotelList.deserializeBinary
);


/**
 * @param {!proto.hotelPackage.noParams} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hotelPackage.HotelList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hotelPackage.HotelList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hotelPackage.HotelsClient.prototype.getFavorite =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hotelPackage.Hotels/getFavorite',
      request,
      metadata || {},
      methodDescriptor_Hotels_getFavorite,
      callback);
};


/**
 * @param {!proto.hotelPackage.noParams} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hotelPackage.HotelList>}
 *     Promise that resolves to the response
 */
proto.hotelPackage.HotelsPromiseClient.prototype.getFavorite =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hotelPackage.Hotels/getFavorite',
      request,
      metadata || {},
      methodDescriptor_Hotels_getFavorite);
};


module.exports = proto.hotelPackage;

